### ISSUE TITLE
Error message with nicfi_mosaics

### ISSUE THREAD

**Issue by PPierre22** [mlampros/PlanetNICFI#1]
I installed the package following instructions on the tutorial (for WIN10). Aria2 is responsive – no apparent issue. GDAL is installed through the source version of sf (using RTools), and the sf package itself works just fine. I tried the CRAN and the source version of PlanetNICFI. In a nutchell, everything seems fine. 

Yet, I cannot get the very first command line of the PlanetNICFI tutorial to work (nicfi_mosaics). I use the example on the help page of the “nicfi_mosaics” function. Every time, I get the following error message:

**mosaic_files = nicfi_mosaics(planet_api_key = api_key,
                                     type = 'monthly',
                                     crs_bbox = 4326,
                                     URL = 'https://api.planet.com/basemaps/v1/mosaics',
                                     verbose = TRUE)**

_Error in data.table::setDT(item) : 
  All elements in argument 'x' to 'setDT' must be of same length, but the profile of input lengths (length:frequency) is: [0:3, 1:19]
The first entry with fewer than 1 entries is 3_

Would that ring any kind of bell? Since there seems to be no issue with the installation, I’m not sure where to dig from here. 

_Here's my session info : 

- Session info -----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio_

**Comment by mlampros** [comment]
Hi @PPierre22, 

an easy way to debug this error and find which sublist of the 'item' object does not have the same length is to move the parameters outside of the **nicfi_mosaics()** function 

```R
planet_api_key = 'your api key'
type = 'monthly'
crs_bbox = 4326
URL = 'https://api.planet.com/basemaps/v1/mosaics'
verbose = TRUE
```
and then to run [line by line the code](https://github.com/mlampros/PlanetNICFI/blob/master/R/nicfi_utils.R#L158-L217). Moreover I would suggest to replace the [lapply() function](https://github.com/mlampros/PlanetNICFI/blob/master/R/nicfi_utils.R#L167-L211) with a for-loop,

```R
mosaics = list()

count = 1

for (x in mosaics) {                                                 # extract the information of all mosaics (including the id's)
  
  cat(count, '\n')
  
  nam_trunc = gsub('planet_medres_normalized_analytic_', '', x$name)
  nam_trunc = gsub('_mosaic', '', nam_trunc)
  nam_trunc = ifelse(nchar(nam_trunc) > 7, 'bi_annually', 'monthly')

  .........

  item[['months']] = length(seq(from = item$first_acquired, to = item$last_acquired, by = '1 months')) - 1
  item$first_acquired = as.character(item$first_acquired)
  item$last_acquired = as.character(item$last_acquired)
  
  item = data.table::setDT(item)
  mosaics[[count]] = item
  count = count + 1
})

```
so that you can find out which of the 

```R
item = data.table::setDT(item)
```
throws the error.

Let me know and make sure that you don't copy paste here the planet api key.

**Comment by PPierre22** [comment]
Hi,

Thank you for your prompt response – and for the tip. 

So, the issue occurs at all iteration of the loop. At any given iteration, the item contains 3 NULL values in the list : 

_> str(item)
List of 22
 $ id            : chr "48fff803-4104-49bc-b913-7467b7a5ffb5"
 $ link_self     : chr "https://api.planet.com/basemaps/v1/mosaics/48fff803-4104-49bc-b913-7467b7a5ffb5?api_key="
 $ link_quads    : **NULL**
 $ link_tiles    : **NULL**
 $ xmin          : int -179
 $ ymin          : int -56
 $ xmax          : int 180
 $ ymax          : int 58
 $ mosaic_wkt    : chr "POLYGON ((-179 -56, 180 -56, 180 58, -179 58, -179 -56))"
 $ epsg          : chr "EPSG:3857"
 $ datatype      : chr "byte"
 $ first_acquired: chr "2016-01-01"
 $ last_acquired : chr "2016-02-01"
 $ quad_size     : int 2048
 $ resolution    : num 4.78
 $ item_types    : chr "PSScene3Band-REOrthoTile"
 $ level         : int 15
 $ name          : chr "global_monthly_2016_01_mosaic"
 $ product_type  : chr "timelapse"
 $ quad_download : **NULL**
 $ type          : chr "bi_annually"
 $ months        : num 1_

I thus edited the function to fill-in those NULL values with a character string (“blablabla”), it does fix the issue for now but I suppose it may be a problem later on, when we need those metadata... Unless we do not need them? 

Thanks

**Comment by mlampros** [comment]
@PPierre22,

I made a mistake because in the function I overwrite the *mosaics* list. Can you try once again using

```R

mosaics_res = list()

count = 1

for (x in mosaics) {   

..........

  item = data.table::setDT(item)
  mosaics_res[[count]] = item
  count = count + 1
}

```

and report back.
You have to rename the outer list to **mosaics_res**. And please **don't forget to remove the API key** in case you copy paste code

**Comment by PPierre22** [comment]
Hey,

Yeah, I noticed you overwrote ‘mosaics’ in the code you proposed, so I changed the name of the outer list already.

The loop stops at iteration 1 and throws an error (because of the NULL values I talked about). When I edit the loop to fill-in the NULL values, the problem is fixed. 

However, at step 2 of the tutorial, when I use the nicfi_quads_bbox function, I get the very same error message (so I’m now trying to debug this one). In this case, this is the **"quad_link_download"** which return NULL values, and this one seems like an important one, unfortunately. 

In case you want to double-check, here is the code that throw the error :

###
planet_api_key = planet_api_key 
type = "monthly" 
crs_bbox = 4326 
URL = "https://api.planet.com/basemaps/v1/mosaics"
verbose = FALSE 

if (verbose) 
    t_start = proc.time()
  if (!type %in% c("monthly", "bi_annually")) 
    stop("The 'type' parameter must be either 'monthly' or 'bi_annually'!", 
         call. = F)
  query_response = httr::GET(url = URL, config = httr::authenticate(user = planet_api_key, 
                                                                    password = ""))
  content_response = httr::content(x = query_response, as = "parsed")
  link = content_response$`_links`$`_self`
  mosaics = content_response$mosaics
  ###
  mosaics_v2 = list()
  count = 1
  for (i in 1:length(mosaics)) {                                                
    
    cat(count, '\n')
    
    x = mosaics[[i]]
    
    nam_trunc = gsub('planet_medres_normalized_analytic_', '', x$name)
    nam_trunc = gsub('_mosaic', '', nam_trunc)
    nam_trunc = ifelse(nchar(nam_trunc) > 7, 'bi_annually', 'monthly')
    
    bbx = as.vector(unlist(x$bbox))
    plg = sf::st_bbox(c(xmin = bbx[1], ymin = bbx[2], xmax = bbx[3], 
                        ymax = bbx[4]), crs = sf::st_crs(crs_bbox))
    plg = sf::st_as_sfc(plg, crs = crs_bbox)
    plg = sf::st_as_text(plg)
    item = list(id = x$id, link_self = x$`_links`$`_self`, 
                link_quads = x$`_links`$quads, link_tiles = x$`_links`$tiles, 
                xmin = bbx[1], ymin = bbx[2], xmax = bbx[3], ymax = bbx[4], 
                mosaic_wkt = plg, epsg = x$coordinate_system, datatype = x$datatype, 
                first_acquired = as.Date(x$first_acquired), last_acquired = as.Date(x$last_acquired), 
                quad_size = x$grid$quad_size, resolution = x$grid$resolution, 
                item_types = paste(unlist(x$item_types), collapse = "-"), 
                level = x$level, name = x$name, product_type = x$product_type, 
                quad_download = x$quad_download, type = nam_trunc)
    
    item[['months']] = length(seq(from = item$first_acquired, to = item$last_acquired, by = '1 months')) - 1
    item$first_acquired = as.character(item$first_acquired)
    item$last_acquired = as.character(item$last_acquired)
    
    # item$link_quads = "bla"
    # item$link_tiles = "bla"
    # item$quad_download = "bla"
    
    item = data.table::setDT(item)
    mosaics_v2[[count]] = item
    count = count + 1
  }

###

**which returns** 

`1 
Error in data.table::setDT(item) : 
  All elements in argument 'x' to 'setDT' must be of same length, but the profile of input lengths (length:frequency) is: [0:3, 1:19]
The first entry with fewer than 1 entries is 3`

**Uncommenting** 

    # item$link_quads = "bla"
    # item$link_tiles = "bla"
    # item$quad_download = "bla"

**fix the issue**

**Comment by mlampros** [comment]
@PPierre22  the **mosaics** list is created after running the **httr::content()** function

```R
query_response = httr::GET(url = URL, config = httr::authenticate(user = planet_api_key, password = ""))
content_response = httr::content(x = query_response, as = "parsed")


```
therefore I would expect by using a valid api key to receive the required quad links (as I do)

```R
str(content_response$mosaics[[1]])

```
Do you receive a 

```R

query_response$status_code
200
```

**Comment by PPierre22** [comment]
Yes, i do receive 200.

If we go down in the code, within the loop, for a given "x" you are creating the object "item" but you are calling in "x" information that do not exist on my side (for instance _link_quads_, _link_tiles_, _quad_download_ - and very similarly _`_links`$download_ in the _nicfi_quads_bbox_ function). 

Here is the structure of x (at one iteration) that i obtain: 

> str(x)
List of 13
 $ _links           :List of 1
  ..$ _self: chr "https://api.planet.com/basemaps/v1/mosaics/48fff803-4104-49bc-b913-7467b7a5ffb5?api_key=MY KEY"
 $ bbox             :List of 4
  ..$ : int -179
  ..$ : int -56
  ..$ : int 180
  ..$ : int 58
 $ coordinate_system: chr "EPSG:3857"
 $ datatype         : chr "byte"
 $ first_acquired   : chr "2016-01-01T00:00:00.000Z"
 $ grid             :List of 2
  ..$ quad_size : int 2048
  ..$ resolution: num 4.78
 $ id               : chr "48fff803-4104-49bc-b913-7467b7a5ffb5"
 $ interval         : chr "1 mon"
 $ item_types       :List of 2
  ..$ : chr "PSScene3Band"
  ..$ : chr "REOrthoTile"
 $ last_acquired    : chr "2016-02-01T00:00:00.000Z"
 $ level            : int 15
 $ name             : chr "global_monthly_2016_01_mosaic"
 $ product_type     : chr "timelapse"

**Comment by mlampros** [comment]
@PPierre22 did you follow the suggested registration in [https://www.planet.com/nicfi/](https://www.planet.com/nicfi/) ? In this page is mentioned **"Current Planet data users will need to sign up with a different email not associated with their Planet account"**
Therefore if you are a Planet user with a different account then you have to re-register with a different e-mail address and receive an API key specifically for the NICFI data. Just to ask in case you are already a Planet user

**Comment by mlampros** [comment]
I'm wondering because the **quads** are required for the next functions so that you can download the data. They actually must exist.

**Comment by mlampros** [comment]
This must be actually the case because from what I see in your 

```R
str(x)

$ item_types :List of 2
..$ : chr "PSScene3Band"
..$ : chr "REOrthoTile"

```
you are missing the 

```R

 $ item_types       :List of 1
  ..$ : chr "PSScene4Band"

```
which is the type of the NICFI data

**Comment by PPierre22** [comment]
Well, I created a new account this very day from https://www.planet.com/nicfi/. 
I'm inspecting my account detail and there is no mention of NICFI, and it's mention "Global AOI Trial" under "Plan Subscriptions", with details such as "Charged Every Download" under "Download Plan" - which is fairly suspicious.
I'll investigate, probably create another account with yet another email adress - then try again. 
I'll let you know, thank you for your reactivity.

**Comment by PPierre22** [comment]
My bad - you were correct. The two functions works fine now that i do have proper access to NICFI data. 
Thank you.

**Comment by mlampros** [comment]
good to hear that and thanks for reporting the issue. I'll add an error case if the "PSScene4Band" does not exist.
